name: blablador310
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - graphviz
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.5.1
  - bottleneck=1.3.7
  - numexpr=2.8.7
  - pip:
      - faiss-cpu
      - fastapi
      - lxml
      - numpy==1.26.4
      - openai
      - pillow
      - pymupdf
      - pypdf
      - python-dotenv
      - python-multipart
      - pytesseract
      - requests
      - sentence-transformers
      - streamlit
      - streamlit-autorefresh
      - graphviz
      - torch            # pip gets you best CUDA versioning if relevant
      - transformers
      - tqdm
      - uvicorn
      - watchdog
      - rank_bm25
      - spacy
      - fastcoref
      - PyYAML
      - pydantic>=2      # v2+ for pydantic-settings compatibility
      - pydantic-settings
      - colbert-ai
