name: blablador310
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - faiss-cpu
      - fastapi
      - lxml
      - numpy
      - openai
      - pandas
      - pillow
      - pymupdf
      - pypdf
      - python-dotenv
      - pytesseract
      - requests
      - sentence-transformers
      - streamlit
      - torch            # pip gets you best CUDA versioning if relevant
      - transformers
      - tqdm
      - uvicorn
      - watchdog
      - rank_bm25
      - spacy
      - fastcoref
      - PyYAML
      - pydantic>=2      # v2+ for pydantic-settings compatibility
      - pydantic-settings
      - colbert-ai